[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "discoeb"
version = "0.1.0"
dependencies = [
    "jax[cuda12]",
    "diffrax",
    "equinox",
    "jaxtyping",
    "jax_cosmo",
    "setuptools<67",
    "lineax",
    "xprof>=2.21.6",
    "tensorflow>=2.20.0",
    "pytest>=8.4.2",
    "pytest-benchmark>=5.2.3",
    "pytest-regressions>=2.8.3",
    "camb>=1.6.0",
    "pandas>=2.3.3",
    "matplotlib>=3.9.4",
]
authors = [{ name = "Oliver Hahn", email = "oliver.hahn@univie.ac.at" }]

description = "..."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Astronomy",
]
[project.optional-dependencies]
dev = ["pytest", "pytest-benchmark", "pytest-regressions", "camb>=1.6.0", "classy>=3.3.4.0", "ipykernel>=6.31.0", "matplotlib>=3.9.4", "pandas"]
docs = ["sphinx", "nbsphinx"]

[project.urls]
Homepage = "https://github.com/ohahn/DISCO-EB"
Issues = "https://github.com/ohahn/DISCO-EB/issues"
Repository = "https://github.com/ohahn/DISCO-EB.git"
